# Assignment 3

In [1]:
import numpy as np
#numpy.arange(start,stop,step)
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [2]:
import numpy as np

#Accept two lists of 5 elements each from user
#Declare empty lists to where you want to append user input
list1=[]
list2=[]
#Given 5 elements to accept for each list from user
for i in range(5):
    #Accepting 5 elements for list1
    n1=int(input())
    #Adding the user input to list1
    list1.append(n1)
for j in range(5):
    #Accepting 5 elements for list2
    n2=int(input())
    #Adding the user input to list2
    list2.append(n2)
#Displaying the lists
print(list1)
print(list2)

#Converting list into numpy arrrays
array1=np.array(list1)
array2=np.array(list2)

#Concatenating arrays
array3=np.concatenate((array1,array2))
print(array3)
#Sorting arrays
print(np.sort(array3))

1
2
3
4
5
6
7
8
9
1
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 1]
[1 2 3 4 5 6 7 8 9 1]
[1 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
# Printing array dimensions
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)


No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


In [4]:
import numpy as np

arr=np.arange(int(input()))
print("Test 1D array (shape) :",arr.shape)

two_d_array_row=arr[np.newaxis]
print("Test 2D array for row is :",two_d_array_row.shape)

two_d_array_col=arr[:, np.newaxis]
print("Test 2D array for column is :",two_d_array_col.shape)

10
Test 1D array (shape) : (10,)
Test 2D array for row is : (1, 10)
Test 2D array for column is : (10, 1)


In [5]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
print("Horizontally stacked:")
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 20)
 
# Stack arrays in sequence vertically (row wise).
print("Vertically stacked")
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 20)

Horizontally stacked:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
--------------------
Vertically stacked
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------


In [6]:
import numpy as np

arr=np.array([4,7,8,9,5,6,5,4,4])

unique,counts=np.unique(arr,return_counts=True)
arr=np.asarray((unique,counts)).T
print(arr)

[[4 3]
 [5 2]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
